### ISSUE TITLE
How to connect to FTP?

### ISSUE THREAD

**Issue by Samdo2** [M4DM0NK3Y/VSCode-Extension-LiveWorkspace#12]
Hello! I use VSC for the first time and I don't know how to configure LiveWorkspace. I installed the extension, what should I do next? I must to create any file with settings or what? Tell me please) Thanks in advance.

**Comment by KR34T1V** [comment]
Hey @Samdo2,
"
### Step 2:

Run the setup command to create a settings template within your workspace. To do this:

Open the command palette:
>Press F1

>Search `'Setup Live Workspace'`

>Run Setup
"

There is an autorun command, mentioned in Step 2 of the user guide which you can find here:
https://github.com/M4DM0NK3Y/VSCode-Extension-LiveWorkspace/blob/master/UserGuide.md

Hope it helps!
